sudo: false
dist: xenial
language: python
cache: pip

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27,codecov
  - python: "3.4"
    env: TOXENV=py34,codecov
  - python: "3.5"
    env: TOXENV=py35,codecov
  - python: "3.6"
    env: TOXENV=py36,codecov
  - python: "3.7"
    env: TOXENV=py37,codecov
  - python: "3.6"
    env: TOXENV=docs

install:
  pip install -U tox

script:
  - tox

notifications:
  email: false
